# fly.toml app configuration file generated for mcavanaugh8-github-io on 2024-04-20T21:58:17-04:00
#
# See https://fly.io/public/reference/configuration/ for information about how to use this file.
#

app = 'mcavanaugh8-github-io'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
