const sourceMike = [
  "Trevor Lawrence",
  "Zach Wilson",
  "Trey Lance/Mac Jones",
  "Kyle Pitts",
  "Penei Sewell/Jamarr Chase",
  "Jamarr Chase/Penei Sewell",
  "Justin Fields/Jaylen Waddle",
  "Rashawn Slater",
  "Patrick Surtain II",
  "Jaycee Horn",
  "Jaylen Waddle",
  "Devonta Smith",
  "Christian Darrisaw",
  "Alijah Vera-Tucker",
  "Mac Jones",
  "Jeremiah Owusu-Koramoah",
  "Kwity Paye",
  "Jaelen Phillips",
  "Micah Parsons",
  "Teven Jenkins",
  "Caleb Farley",
  "Rashod Bateman",
  "Greg Newsome II",
  "Samuel Cosmi/Creed Humphrey",
  "Alex Leatherwood",
  "Christian Barmore",
  "Liam Eichenberg",
  "Asante Samuel Jr.",
  "Elijah Moore",
  "Travis Etienne",
  "Trevon Moehrig",
  "Levi Onwuzurike",
];

const sourceCarney = [
  "Trevor Lawrence",
  "Zach Wilson",
  "Trey Lance/Mac Jones",
  "Kyle Pitts",
  "Jamarr Chase/Penei Sewell",
  "Jaylen Waddle",
  "Penei Sewell",
  "Rashawn Slater",
  "Justin Fields",
  "Patrick Surtain II",
  "Devonta Smith",
  "Jaycee Horn/Justin Fields",
  "Kwity Paye/Rashawn Slater",
  "Alijah Vera-Tucker",
  "Mac Jones",
  "Caleb Farley",
  "Micah Parsons",
  "Zaven Collins",
  "Jeremiah Owusu-Koramoah",
  "Christian Darrisaw",
  "Jaelan Phillips",
  "Elijah Moore",
  "Greg Newsome II/Travis Etienne",
  "Najee Harris",
  "Teven Jenkins",
  "Jamin Davis",
  "Jayson Oweh",
  "Tyson Campbell",
  "Landon Dickerson",
  "Travis Etienne",
  "Liam Eichenberg",
  "Joe Tryon",
];

const sourceAndrew = [
  "Trevor Lawrence",
  "Zach Wilson",
  "Mac Jones",
  "Kyle Pitts",
  "Jamarr Chase/Penei Sewell",
  "Jaylen Waddle/Jamarr Chase",
  "Penei Sewell/Rashawn Slater",
  "Patrick Surtain II/Justin Fields",
  "Justin Fields/Trey Lance",
  "Jaycee Horn",
  "Devonta Smith",
  "Micah Parsons",
  "Rashawn Slater",
  "Alijah Vera-Tucker",
  "Trey Lance",
  "Zaven Collins",
  "Christian Darrisaw",
  "Kwity Paye",
  "Jeremiah Owusu-Koramoah",
  "Teven Jenkins",
  "Caleb Farley",
  "Kadarius Toney",
  "Greg Newsome II",
  "Najee Harris",
  "Jaelan Phillips",
  "Zaven Collins",
  "Azeez Ojulari",
  "Asante Samuel Jr.",
  "Jamin Davis",
  "Aaron Robinson",
  "Rashod Bateman",
  "Gregory Rousseau",
];
